#[aspen]
#Sprint51-Prod-Crossmerge-to-DEV01:kdhakal@deloitte.com,hadevaraj@deloitte.com,rbandla@deloitte.com
#DEV03-ASPEN-175697-Team-Willow:srvasireddy@deloitte.com,bacherukuri@deloitte.com,kdhakal@deloitte.com,hadevaraj@deloitte.com
#DEV03-ASPEN-156582-MMISR-Custom-MFT:chachava@deloitte.com,vakolli@deloitte.com,kdhakal@deloitte.com,hadevaraj@deloitte.com
[database]
Sprint51-Prod-Crossmerge-to-DEV01:kdhakal@deloitte.com,hadevaraj@deloitte.com,rbandla@deloitte.com
#DEV03-AM-15074-CYFD-Integration:chachava@deloitte.com,vakolli@deloitte.com,kdhakal@deloitte.com,hadevaraj@deloitte.com
#DEV03-ASPEN-175697-Team-Willow:srvasireddy@deloitte.com,bacherukuri@deloitte.com,kdhakal@deloitte.com,hadevaraj@deloitte.com
#DEV03-ASPEN-156582-MMISR-Custom-MFT:chachava@deloitte.com,vakolli@deloitte.com,kdhakal@deloitte.com,hadevaraj@deloitte.com
#[hpx]
#Cross-Merge-Test-Branch:kdhakal@deloitte.com,hadevaraj@deloitte.com
#EOD config file